### ISSUE TITLE
Enhancement: Option to save the log on "launch" instead of on closing the game.

### ISSUE THREAD

**Issue by Porcar** [notsigma/NWNLogRotator#13]
This is particularly useful in case the crashes or something similar.

**Comment by notsigma** [comment]
This is doable, I'll add it to the list. I need to think about the implementation!

**Comment by Albacksen** [comment]
I want to second that his would be useful. I've lost logs because I've been too quick to restart the game upon crashing. This would definitely be an ace feature.

**Comment by notsigma** [comment]
Please try https://github.com/notsigma/NWNLogRotator/releases/tag/v0.8.4 

And report feedback, positive or negative, it helps alot : )

**Comment by Porcar** [comment]
It saves the log on open now, awesome! but the program closes when the nwn client does as well even if the option to do so is not active.

**Comment by notsigma** [comment]
Sorry about that, will look into it soon and hopefully a patch will be along shortly.

**Comment by Porcar** [comment]
Fixed!
