### ISSUE TITLE
Lines minimum to save log feature not functioning correctly?

### ISSUE THREAD

**Issue by n0cturn41** [notsigma/NWNLogRotator#3]
Case example:
Currently set to 20 lines minimum in config.
![log1](https://user-images.githubusercontent.com/64118292/83919712-4c655680-a7cf-11ea-860d-07848b8d99ab.png)

Logging into the player list of a server then quit the game. nwclientLog1 has 9 lines:
[nwclientLog1.txt](https://github.com/notsigma/NWNLogRotator/files/4738324/nwclientLog1.txt)

Log is still automatically created:
![log2](https://user-images.githubusercontent.com/64118292/83919764-7159c980-a7cf-11ea-8a96-05c16ce004c0.png)

When attempting to set it to, say, 30 lines minimum, even several hour sessions with hundreds of lines are then interpreted to not have enough lines and the log is not saved.

Many thanks

**Comment by notsigma** [comment]
When I wrote this, I counted the number of lines with actors, because that was originally the intention of a "line". So if Bob Smith spoke 10 lines, that was "10 lines"

In your example, nobody is speaking lines, so they wouldn't count. I will look into changing this (it's easy to fix, but need to test it), since this should really just be counting lines and nothing complicated.

The code for reference:
https://github.com/notsigma/NWNLogRotator/blob/master/Components/FileHandler.cs#L343

**Comment by notsigma** [comment]
Please let me know how v0.4.8 does. It should count literal lines now. Thanks for the feedback!

**Comment by n0cturn41** [comment]
So, ran a session for some hours. Closed the game and the application responded with:
![log1a](https://user-images.githubusercontent.com/64118292/83939730-4dc86a80-a833-11ea-85e2-080498a57311.png)

Settings are same as initial post, save I've unchecked 'Remove Event Text'.

nwclinetLog1 is several hundred lines.

**Comment by notsigma** [comment]
I am very curious about log file it parsed. Are most of the lines removed? Can you please get a copy of one of the larger files?

**Comment by n0cturn41** [comment]
Thanks for the quick replies. Unfortunately the nwclientlog was overwritten this morning before I checked but I'll try get another session's copy.

This is on the server [Ravenloft: Prisoners of the Mist]

Filter lines currently are:
Unknown Update sub-message,The time is now,Progression by roleplay...,Experience gained,You are now in a Full PVP Area,Driving Camera Activated,Top Down Camera Activated,Failed to save configuration: rename of .tmp failed: 17,Your cryptographic public identity is:

**Comment by n0cturn41** [comment]
Another session, tool works when set to less than 7 lines, but actual log is hundreds.
[nwclientLog1.txt](https://github.com/notsigma/NWNLogRotator/files/4742872/nwclientLog1.txt)

Here is the config file:
MinimumRows=7
ServerName=
ServerNameColor=
EventText=True
CombatText=True
UseTheme=dark
Silent=True
Tray=True
SaveBackup=False
Notifications=True
CustomEmotes=
FilterLines=Unknown Update sub-message,The time is now,Progression by roleplay...,Experience gained,You are now in a Full PVP Area,Driving Camera Activated,Top Down Camera Activated,Failed to save configuration: rename of .tmp failed: 17,Your cryptographic public identity is:

**Comment by notsigma** [comment]
This issue should be completely resolved. Thank you for reporting it, and being patient and thorough. Please re-open this issue if it's still not working, but it should be set.
