### ISSUE TITLE
Whispers and Tells not recorded in new log

### ISSUE THREAD

**Issue by n0cturn41** [notsigma/NWNLogRotator#4]
Hi! Me again. 

Did some comparisons in v.0.5.0. Doesn't look like it picked up [Whisper] or [Tell]'s.

e.g. Observe timestamps:
![log1](https://user-images.githubusercontent.com/64118292/83998635-239eb600-a9b5-11ea-905e-1ec82a088090.png)

![log2](https://user-images.githubusercontent.com/64118292/83998640-24cfe300-a9b5-11ea-9fb7-ec743ac6b0d2.png)
-----
![log3](https://user-images.githubusercontent.com/64118292/83998829-8c862e00-a9b5-11ea-8ceb-4fc5d8e38b8f.png)

![log4](https://user-images.githubusercontent.com/64118292/83998835-8f811e80-a9b5-11ea-9a80-e753f0d874b1.png)

Removing filter lines didn't have an impact.

**Comment by notsigma** [comment]
I'm looking into fixing this properly. For now, please save your logs with "Save Backup" incase you want to parse them when it's fixed. Hope thats very soon.

**Comment by notsigma** [comment]
v0.5.1 is out and works with my logs. Please let me know if this fixes your problem. Thanks again for reporting it, and I'm sorry it happened.

Every server has their own way of doing things, lol.

**Comment by n0cturn41** [comment]
No apologies necessary, thanks for following up and supporting the tool, greatly appreciated and welcomed.

**Comment by notsigma** [comment]
Please reply or raise a new issue if this is still a problem. As far as I can see, it's completely fixed.
