### ISSUE TITLE
"View Log" Message Duplication

### ISSUE THREAD

**Issue by Phoosy** [notsigma/NWNLogRotator#6]
Each time the game is closed and launched there seems to be a running 'counter' that will pop up a new instance alert message that a log was created with a yes/no to view it, +1 each time the game is opened/closed while logrotater is open.

Ex:
Open game with logrotater, close, 1 message
Open game again with logrotater, close, 2 messages
repeat

**Comment by notsigma** [comment]
I will look into this. Thanks for reporting it!

**Comment by notsigma** [comment]
I am not able to reproduce this, following the steps you have provided.

What I did:
1) Started NWN Log Rotator with no launcher parameters configured.
2) Opened NWN EE from steam, joined server, spammed a few lines, closed
3) Clicked ok to view the log.
4) Repeated steps 2 and 3.

I only received 1 prompt each time.

- Are you using the latest version?
- Did your steps differ at all from the above?

**Comment by Phoosy** [comment]
Not sure what would have changed in 0.7.0 that addressed this but it does not seem to happen anymore.
