### ISSUE TITLE
A couple of additional suggestions!

### ISSUE THREAD

**Issue by n0cturn41** [notsigma/NWNLogRotator#7]
Once again, thanks for this. It's great.
Further, would it be possible to:

1. Define your own character name in the settings, and the HTML output colours that name differently. This way it differentiates your lines as opposed to other actors.
2. Run a different set of settings based on server you connect to. -- Not sure how this might be done if the input log doesn't differentiate. Possible to do based on nwmain.exe/IP address of server/name of direct connect shortcut?
The advantage of this is that you might have different filter lines for different servers, or other options.

Cheers!

**Comment by n0cturn41** [comment]
For #2, actually, I just realised (after watching your video) I can use multiple .exe's in different folders and use the launcher instead of the direct connect shortcuts I have which might solve this request.

**Comment by notsigma** [comment]
I'll add #1 to the list - it's possible.

**Comment by notsigma** [comment]
Go ahead and try that please! (0.6.3 now has it in the export options)

**Comment by n0cturn41** [comment]
Thanks. Applies character colour correctly (tested one character). However this has now removed other text colours, i.e. Tells, Whispers.[https://i.gyazo.com/d8562af18fe2851c8dae9924aaa80024.png](url)

**Comment by notsigma** [comment]
Sorry about that, please try 0.6.4.

**Comment by n0cturn41** [comment]
Colours look good. One thing with the unique case for servers.

Ravenloft works OK:
![test-raven](https://user-images.githubusercontent.com/64118292/94870458-10ec4780-04a4-11eb-8df3-8f836fc095b6.png)

Arelith missing whispers because of their language system or delimiters(?):
![test-arel](https://user-images.githubusercontent.com/64118292/94870462-134ea180-04a4-11eb-909d-e9e76f36676d.png)

Cheers.

**Comment by notsigma** [comment]
Good catch. Should be fixed now in v0.6.6!

**Comment by n0cturn41** [comment]
I'll raise a new issue if I see it. Thanks!
