### ISSUE TITLE
Notifications do not generate on launcher auto-close

### ISSUE THREAD

**Issue by n0cturn41** [notsigma/NWNLogRotator#8]
As per title. With two settings enabled:
1. 'Notifications'
2. 'Close Launcher Automatically when Client closes'

Result:
a). Notifications don't have a chance to appear before the application closes after the output is generated. Introducing a 5 second pause before closure might work.
b). Clicking 'Run Once' while the 'Close Launcher Automatically when Client closes' setting is enabled, closes the LogRotator.

Cheers

**Comment by notsigma** [comment]
Should be fixed now in v0.6.6!

**Comment by n0cturn41** [comment]
Yep, all good, thanks.
