### ISSUE TITLE
Cant set "//" as custom emote

### ISSUE THREAD

**Issue by Porcar** [notsigma/NWNLogRotator#9]
Awesome tool! 

Tried setting // as a custom emote, but it makes all the HTML look weird.

![image](https://user-images.githubusercontent.com/7613237/96084206-acaa8a00-0e8c-11eb-8bf5-5841c70611aa.png)

Another thing is a suggestion: is there a way to set different colors to custom emotes. For example on the server I'm playing we use: 

* asdasd* for emotes -> (blue)
// for OOC  -> (red)
( asdas ) for thoughts ->  (green)

Thanks!

**Comment by notsigma** [comment]
Working on fixing this issue and looking into the other one! It might take a little bit, but I hope to get them addressed soon.

**Comment by notsigma** [comment]
This is in 0.7.7!
